### ISSUE TITLE
Why not in to app

### ISSUE THREAD

**Issue by fajarwahyu99** [thetmcteam/tickets#10]
![gambar](https://user-images.githubusercontent.com/11350854/37013215-6474a866-212b-11e8-8f98-99ce5dd65a44.png)
 i was login use admin secret
after that not launch app. why?

![gambar](https://user-images.githubusercontent.com/11350854/37013240-7a0d5e48-212b-11e8-9d0b-e5c6d6e3d98c.png)

**Comment by jordanbardsley7** [comment]
Run `php artisan serve` from the root of the project.

**Comment by fajarwahyu99** [comment]
yes i did it but until now , i cant login to app
