### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Wipsly** [thetmcteam/tickets#5]
Hi,

i followed the instruction, but I get "unauthorized" in chrome dev tools if i try to login with admin secret.

Any idea?

**Comment by jordanbardsley7** [comment]
Was re-hashing the password, this should fix it - https://github.com/thetmcteam/tickets/pull/6. Feel free to pull down the changes and re-seed your database.

**Comment by Wipsly** [comment]
Now i get

SCRIPT5009: "Promise" is undefined
app.js (1,308809)

**Comment by jordanbardsley7** [comment]
The Polyfill needs to be imported into the entry point script. Feel free to send us over a PR and we can get it merged.
